# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    WORKSPACEID = "workspaceid"
    HOSTID = "hostid"
    

class Output:
    STATUSCODE = "statuscode"
    STATUS = "status"
    LOOTS = "loots"
    

class LootsInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"hostid": {
			"type": "string",
			"title": "主机id",
			"description": "",
			"order": 2
		},
		"workspaceid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 1
		}
	}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class LootsOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"loots": {
			"type": "array",
			"title": "收集的信息",
			"description": "",
			"order": 3,
			"items": {
				"type": "object"
			}
		},
		"status": {
			"type": "string",
			"title": "结果",
			"description": "",
			"order": 2
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
