# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    WORKSPACEID = "workspaceid"
    TASKID = "taskid"
    

class Output:
    STATUSCODE = "statuscode"
    STATUS = "status"
    RESULT = "result"
    ERROR = "error"
    

class ValidatevulnsresultsInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"taskid": {
			"type": "string",
			"title": "任务id",
			"description": "",
			"order": 2
		},
		"workspaceid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"workspaceid",
		"taskid"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ValidatevulnsresultsOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"error": {
			"type": "string",
			"title": "失败原因",
			"description": "",
			"order": 4
		},
		"result": {
			"type": "array",
			"title": "漏洞验证结果数组",
			"description": "",
			"order": 3,
			"items": {
				"type": "object"
			}
		},
		"status": {
			"type": "string",
			"title": "漏洞验证结果状态",
			"description": "",
			"order": 2,
			"enum": [
				"running",
				"completed",
				"failed"
			]
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
