# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    WORKSPACESID = "workspacesid"
    HOSTID = "hostid"
    

class Output:
    STATUSCODE = "statuscode"
    DATA = "data"
    

class WorkspaceshostssessionsInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"hostid": {
			"type": "string",
			"title": "主机id",
			"description": "",
			"order": 2
		},
		"workspacesid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"workspacesid",
		"hostid"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class WorkspaceshostssessionsOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"data": {
			"type": "array",
			"title": "返回数据",
			"description": "",
			"order": 2,
			"items": {
				"type": "object"
			}
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
