# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    WORKSPACEID = "workspaceid"
    COLLECTSESSIONS = "collectsessions"
    COLLECTSYSINFO = "collectsysinfo"
    COLLECTPASSWD = "collectpasswd"
    COLLECTSSH = "collectssh"
    COLLECTSCREENSHOTS = "collectscreenshots"
    COLLECTAPPS = "collectapps"
    COLLECTDRIVERS = "collectdrivers"
    COLLECTUSERS = "collectusers"
    COLLECTDOMAIN = "collectdomain"
    COLLECTFILES = "collectfiles"
    COLLECTFILESPATTERN = "collectfilespattern"
    COLLECTFILESCOUNT = "collectfilescount"
    COLLECTFILESIZE = "collectfilesize"
    

class Output:
    STATUSCODE = "statuscode"
    SUCCESS = "success"
    WORKSPACEID = "workspaceid"
    TASKID = "taskid"
    ERRORS = "errors"
    

class TasksstartcollectevidenceInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"collectapps": {
			"type": "boolean",
			"title": "已安装的应用",
			"description": "",
			"order": 7
		},
		"collectdomain": {
			"type": "boolean",
			"title": "主域",
			"description": "",
			"order": 10
		},
		"collectdrivers": {
			"type": "boolean",
			"title": "驱动",
			"description": "",
			"order": 8
		},
		"collectfiles": {
			"type": "boolean",
			"title": "收集其他文件",
			"description": "如果值为true，必须配置collect_files_pattern、collect_files_count和collect_files_size参数对应值，且collect_files_pattern不能为空,collect_files_count\u003e=1, collect_files_size\u003e=0.1",
			"order": 11
		},
		"collectfilescount": {
			"type": "integer",
			"title": "最大文件数量",
			"description": "",
			"order": 13
		},
		"collectfilesize": {
			"type": "number",
			"title": "最大文件大小",
			"description": "",
			"order": 14
		},
		"collectfilespattern": {
			"type": "string",
			"title": "文件名模式",
			"description": "",
			"order": 12
		},
		"collectpasswd": {
			"type": "boolean",
			"title": "系统密码",
			"description": "",
			"order": 4
		},
		"collectscreenshots": {
			"type": "boolean",
			"title": "截屏",
			"description": "",
			"order": 6
		},
		"collectsessions": {
			"type": "array",
			"title": "在线会话",
			"description": "",
			"order": 2,
			"items": {
				"type": "string"
			}
		},
		"collectssh": {
			"type": "boolean",
			"title": "SSH密钥",
			"description": "",
			"order": 5
		},
		"collectsysinfo": {
			"type": "boolean",
			"title": "系统信息",
			"description": "",
			"order": 3
		},
		"collectusers": {
			"type": "boolean",
			"title": "已登录的用户",
			"description": "",
			"order": 9
		},
		"workspaceid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"workspaceid"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class TasksstartcollectevidenceOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"errors": {
			"type": "string",
			"title": "错误信息",
			"description": "",
			"order": 5
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		},
		"success": {
			"type": "string",
			"title": "结果",
			"description": "",
			"order": 2
		},
		"taskid": {
			"type": "string",
			"title": "任务id",
			"description": "",
			"order": 4
		},
		"workspaceid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 3
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
