# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    WORKSPACEID = "workspaceid"
    KNOWNTARGETS = "knowntargets"
    MAXMINUTES = "maxminutes"
    MAXTHREADS = "maxthreads"
    HTTPUSERNAME = "httpusername"
    HTTPPASSWORD = "httppassword"
    HTTPDOMAIN = "httpdomain"
    COOKIE = "cookie"
    USERAGENT = "useragent"
    SESSIONCOOKIENAME = "sessioncookiename"
    DIRECTOBJECTREFERENCE = "directobjectreference"
    

class Output:
    STATUSCODE = "statuscode"
    SUCCESS = "success"
    WORKSPACEID = "workspaceid"
    TASKID = "taskid"
    ERRORS = "errors"
    

class TasksstartwebauditInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"cookie": {
			"type": "string",
			"title": "http Cookie",
			"description": "",
			"order": 8
		},
		"directobjectreference": {
			"type": "boolean",
			"title": "检查不安全的引用对象漏洞",
			"description": "",
			"order": 11
		},
		"httpdomain": {
			"type": "string",
			"title": "http域",
			"description": "",
			"order": 7
		},
		"httppassword": {
			"type": "string",
			"title": "http密码",
			"description": "",
			"order": 6,
			"displayType": "password",
			"format": "password"
		},
		"httpusername": {
			"type": "string",
			"title": "http用户名",
			"description": "",
			"order": 5
		},
		"knowntargets": {
			"type": "string",
			"title": "已知的目标",
			"description": "JSON字符串, //POST /rest_api/v3/tasks/web_data, 返回data数据作为这个参数值",
			"order": 2
		},
		"maxminutes": {
			"type": "integer",
			"title": "爬虫时间限制(min/url)",
			"description": "",
			"order": 3
		},
		"maxthreads": {
			"type": "integer",
			"title": "爬虫并发数",
			"description": "",
			"order": 4
		},
		"sessioncookiename": {
			"type": "string",
			"title": "cookie",
			"description": "",
			"order": 10
		},
		"useragent": {
			"type": "string",
			"title": "用户代理",
			"description": "",
			"order": 9
		},
		"workspaceid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"workspaceid"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class TasksstartwebauditOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"errors": {
			"type": "string",
			"title": "错误信息",
			"description": "",
			"order": 5
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		},
		"success": {
			"type": "string",
			"title": "结果",
			"description": "",
			"order": 2
		},
		"taskid": {
			"type": "string",
			"title": "任务id",
			"description": "",
			"order": 4
		},
		"workspaceid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 3
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
