# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    CONSOLEIP = "consoleip"
    DBUSER = "dbuser"
    DBPASS = "dbpass"
    

class Output:
    STATUSCODE = "statuscode"
    STATUS = "status"
    ERROR = "error"
    

class SyncconfigsyncInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"consoleip": {
			"type": "string",
			"title": "请求IP",
			"description": "",
			"order": 1
		},
		"dbpass": {
			"type": "string",
			"title": "数据库密码",
			"description": "",
			"order": 3,
			"displayType": "password",
			"format": "password"
		},
		"dbuser": {
			"type": "string",
			"title": "数据库用户名",
			"description": "",
			"order": 2
		}
	},
	"required": [
		"consoleip",
		"dbuser",
		"dbpass"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class SyncconfigsyncOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"error": {
			"type": "string",
			"title": "失败原因",
			"description": "",
			"order": 3
		},
		"status": {
			"type": "string",
			"title": "同步数据库结果",
			"description": "",
			"order": 2,
			"enum": [
				"error",
				"success"
			]
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
