# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    NAME = "name"
    DESCRIPTION = "description"
    

class Output:
    STATUSCODE = "statuscode"
    RESULT = "result"
    MESSAGE = "message"
    

class BackupscreateInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"description": {
			"type": "string",
			"title": "备份描述",
			"description": "",
			"order": 2
		},
		"name": {
			"type": "string",
			"title": "备份名称",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"name",
		"description"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class BackupscreateOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"message": {
			"type": "string",
			"title": "数据备份信息",
			"description": "",
			"order": 3
		},
		"result": {
			"type": "string",
			"title": "Result",
			"description": "",
			"order": 2
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode",
		"result"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
