# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    WORKSPACEID = "workspaceid"
    COREIDS = "coreids"
    SERVICEIDS = "serviceids"
    

class Output:
    STATUSCODE = "statuscode"
    SUCCESS = "success"
    WORKSPACEID = "workspaceid"
    TASKID = "taskid"
    ERRORS = "errors"
    

class TasksstartbruteforcereuseInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"coreids": {
			"type": "array",
			"title": "凭证ids",
			"description": "",
			"order": 2,
			"items": {
				"type": "string"
			}
		},
		"serviceids": {
			"type": "array",
			"title": "目标服务ids",
			"description": "",
			"order": 3,
			"items": {
				"type": "string"
			}
		},
		"workspaceid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"workspaceid",
		"coreids",
		"serviceids"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class TasksstartbruteforcereuseOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"errors": {
			"type": "string",
			"title": "错误信息",
			"description": "",
			"order": 5
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		},
		"success": {
			"type": "string",
			"title": "结果",
			"description": "",
			"order": 2
		},
		"taskid": {
			"type": "string",
			"title": "任务id",
			"description": "",
			"order": 4
		},
		"workspaceid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 3
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
