# -*- coding: utf-8 -*
# GENERATED BY CHARIOT SDK - DO NOT EDIT
from setuptools import setup, find_packages


setup(name='yaoguang-chariot-plugin',
      version="0.1.0",
      description='碳泽-摇光 API接口',
      author='chariot',
      author_email='',
      url='',
      packages=find_packages(),
      scripts=['bin/chariot_yaoguang']
      )