# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    ID = "id"
    

class Output:
    STATUSCODE = "statuscode"
    STATUS = "status"
    PATH = "path"
    STATE = "state"
    CONTENT = "content"
    ERROR = "error"
    

class TasklogtotallogInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"id": {
			"type": "string",
			"title": "任务id",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"id"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class TasklogtotallogOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"content": {
			"type": "string",
			"title": "日志内容",
			"description": "",
			"order": 5
		},
		"error": {
			"type": "string",
			"title": "失败原因",
			"description": "",
			"order": 6
		},
		"path": {
			"type": "string",
			"title": "日志路径",
			"description": "",
			"order": 3
		},
		"state": {
			"type": "string",
			"title": "任务状态",
			"description": "",
			"order": 4
		},
		"status": {
			"type": "string",
			"title": "结果",
			"description": "",
			"order": 2,
			"enum": [
				"error",
				"success"
			]
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
