# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    ID = "id"
    LINENO = "lineno"
    LINENUM = "linenum"
    

class Output:
    STATUSCODE = "statuscode"
    STATUS = "status"
    CONTENT = "content"
    STARTLINENO = "startlineno"
    ENDLINENO = "endlineno"
    READSTATE = "readstate"
    ERROR = "error"
    

class TasklogcurrentlogInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"id": {
			"type": "string",
			"title": "任务id",
			"description": "",
			"order": 1
		},
		"lineno": {
			"type": "string",
			"title": "第几行",
			"description": "",
			"order": 2
		},
		"linenum": {
			"type": "string",
			"title": "行数",
			"description": "",
			"order": 3
		}
	},
	"required": [
		"id",
		"lineno",
		"linenum"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class TasklogcurrentlogOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"content": {
			"type": "string",
			"title": "日志内容",
			"description": "",
			"order": 3
		},
		"endlineno": {
			"type": "string",
			"title": "结束行",
			"description": "",
			"order": 5
		},
		"error": {
			"type": "string",
			"title": "失败原因",
			"description": "",
			"order": 7
		},
		"readstate": {
			"type": "string",
			"title": "读取状态",
			"description": "",
			"order": 6,
			"enum": [
				"finished",
				"continued"
			]
		},
		"startlineno": {
			"type": "string",
			"title": "开始行",
			"description": "",
			"order": 4
		},
		"status": {
			"type": "string",
			"title": "结果",
			"description": "",
			"order": 2,
			"enum": [
				"error",
				"success"
			]
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
