# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    UPDATEFILE = "updatefile"
    

class Output:
    STATUSCODE = "statuscode"
    RESULT = "result"
    MESSAGE = "message"
    

class VersionupgradeofflineInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"updatefile": {
			"title": "升级版本文件",
			"description": "",
			"order": 1,
			"$ref": "#/definitions/file"
		}
	},
	"required": [
		"updatefile"
	],
	"definitions": {
		"file": {
			"id": "file",
			"type": "object",
			"title": "File",
			"description": "File Object",
			"properties": {
				"content": {
					"type": "string",
					"title": "Content",
					"description": "File contents",
					"format": "bytes"
				},
				"filename": {
					"type": "string",
					"title": "Filename",
					"description": "Name of file"
				}
			}
		}
	}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class VersionupgradeofflineOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"message": {
			"type": "string",
			"title": "提示信息",
			"description": "",
			"order": 3
		},
		"result": {
			"type": "string",
			"title": "Result",
			"description": "",
			"order": 2
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
