# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    WORKSPACESID = "workspacesid"
    ID = "id"
    

class Output:
    STATUSCODE = "statuscode"
    SUCCESS = "success"
    HOST = "host"
    SERVICES = "services"
    

class WorkspaceshostsdetailInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"id": {
			"type": "string",
			"title": "主机id",
			"description": "",
			"order": 2
		},
		"workspacesid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"workspacesid",
		"id"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class WorkspaceshostsdetailOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"host": {
			"type": "object",
			"title": "主机",
			"description": "",
			"order": 3
		},
		"services": {
			"type": "array",
			"title": "服务数据",
			"description": "",
			"order": 4,
			"items": {
				"type": "object"
			}
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		},
		"success": {
			"type": "string",
			"title": "结果",
			"description": "",
			"order": 2
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
