# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    BACKUPNAME = "backupname"
    

class Output:
    STATUSCODE = "statuscode"
    RESULT = "result"
    MESSAGE = "message"
    

class BackupsrestoreInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"backupname": {
			"type": "string",
			"title": "备份名称",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"backupname"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class BackupsrestoreOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"message": {
			"type": "string",
			"title": "数据备份信息",
			"description": "",
			"order": 3
		},
		"result": {
			"type": "string",
			"title": "Result",
			"description": "",
			"order": 2
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
