# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Input:
    pass
    

class ConnectionSchema(chariot.Input):
    schema = json.loads("""
   {}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)