# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    WORKSPACEID = "workspaceid"
    ID = "id"
    FORMAT = "format"
    

class Output:
    STATUSCODE = "statuscode"
    DATA = "data"
    

class WorkspacesreportsdownloadInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"format": {
			"type": "string",
			"title": "报告文件类型",
			"description": "",
			"order": 3,
			"enum": [
				"html",
				"word",
				"pdf"
			]
		},
		"id": {
			"type": "string",
			"title": "报告Id",
			"description": "",
			"order": 2
		},
		"workspaceid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"workspaceid",
		"id",
		"format"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class WorkspacesreportsdownloadOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"data": {
			"title": "下载文件",
			"description": "",
			"order": 2,
			"$ref": "#/definitions/file"
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	],
	"definitions": {
		"file": {
			"id": "file",
			"type": "object",
			"title": "File",
			"description": "File Object",
			"properties": {
				"content": {
					"type": "string",
					"title": "Content",
					"description": "File contents",
					"format": "bytes"
				},
				"filename": {
					"type": "string",
					"title": "Filename",
					"description": "Name of file"
				}
			}
		}
	}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
