# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    RANDOMSTRING = "randomstring"
    

class Output:
    STATUSCODE = "statuscode"
    STATUS = "status"
    ERROR = "error"
    RANDOMSTRING = "randomstring"
    

class SyncconfigstatusInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"randomstring": {
			"type": "string",
			"title": "随机字符串",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"randomstring"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class SyncconfigstatusOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"error": {
			"type": "string",
			"title": "失败原因",
			"description": "",
			"order": 3
		},
		"randomstring": {
			"type": "string",
			"title": "随机字符串",
			"description": "",
			"order": 4
		},
		"status": {
			"type": "string",
			"title": "同步数据库结果",
			"description": "",
			"order": 2,
			"enum": [
				"error",
				"success"
			]
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
