# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    BACKUPNAME = "backupname"
    

class Output:
    STATUSCODE = "statuscode"
    RESULT = "result"
    

class BackupsdeleteInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"backupname": {
			"type": "array",
			"title": "备份名称",
			"description": "",
			"order": 1,
			"items": {
				"type": "string"
			}
		}
	},
	"required": [
		"backupname"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class BackupsdeleteOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"result": {
			"type": "string",
			"title": "Result",
			"description": "",
			"order": 2
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
