# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    WORKSPACEID = "workspaceid"
    URLS = "urls"
    KNOWNTARGETS = "knowntargets"
    MAXPAGES = "maxpages"
    MAXMINUTES = "maxminutes"
    MAXTHREADS = "maxthreads"
    UNAUTHORIZEDACCESSFORBIDDENPHRASES = "unauthorizedaccessforbiddenphrases"
    SSLREUIRED = "sslreuired"
    REPORTWEAK = "reportweak"
    EXCLUDEPATHPATTERNS = "excludepathpatterns"
    HTTPUSERNAME = "httpusername"
    HTTPPASSWORD = "httppassword"
    HTTPDOMAIN = "httpdomain"
    COOKIE = "cookie"
    USERAGENT = "useragent"
    

class Output:
    STATUSCODE = "statuscode"
    SUCCESS = "success"
    WORKSPACEID = "workspaceid"
    TASKID = "taskid"
    ERRORS = "errors"
    

class TasksstartwebscanInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"cookie": {
			"type": "string",
			"title": "http Cookie",
			"description": "",
			"order": 14
		},
		"excludepathpatterns": {
			"type": "string",
			"title": "排除路径模式",
			"description": "",
			"order": 10
		},
		"httpdomain": {
			"type": "string",
			"title": "http域",
			"description": "",
			"order": 13
		},
		"httppassword": {
			"type": "string",
			"title": "http密码",
			"description": "",
			"order": 12,
			"displayType": "password",
			"format": "password"
		},
		"httpusername": {
			"type": "string",
			"title": "http用户名",
			"description": "",
			"order": 11
		},
		"knowntargets": {
			"type": "string",
			"title": "已知的目标",
			"description": "JSON字符串, //POST /rest_api/v3/tasks/web_data, 返回data数据作为这个参数值",
			"order": 3
		},
		"maxminutes": {
			"type": "integer",
			"title": "爬虫时间限制(min/url)",
			"description": "",
			"order": 5
		},
		"maxpages": {
			"type": "integer",
			"title": "最大爬去行数",
			"description": "",
			"order": 4
		},
		"maxthreads": {
			"type": "integer",
			"title": "爬虫并发数",
			"description": "",
			"order": 6
		},
		"reportweak": {
			"type": "boolean",
			"title": "允许ssl弱密钥报告漏洞",
			"description": "",
			"order": 9
		},
		"sslreuired": {
			"type": "boolean",
			"title": "未启用ssl报告漏洞",
			"description": "",
			"order": 8
		},
		"unauthorizedaccessforbiddenphrases": {
			"type": "string",
			"title": "关键字排除",
			"description": "",
			"order": 7
		},
		"urls": {
			"type": "string",
			"title": "目标urls",
			"description": "",
			"order": 2
		},
		"useragent": {
			"type": "string",
			"title": "用户代理",
			"description": "",
			"order": 15
		},
		"workspaceid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"workspaceid",
		"urls"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class TasksstartwebscanOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"errors": {
			"type": "string",
			"title": "错误信息",
			"description": "",
			"order": 5
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		},
		"success": {
			"type": "string",
			"title": "结果",
			"description": "",
			"order": 2
		},
		"taskid": {
			"type": "string",
			"title": "任务id",
			"description": "",
			"order": 4
		},
		"workspaceid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 3
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
