# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    WORKSPACESID = "workspacesid"
    HOSTID = "hostid"
    SERVICEID = "serviceid"
    WEBSITESID = "websitesid"
    ID = "id"
    

class Output:
    STATUSCODE = "statuscode"
    DATA = "data"
    

class WorkspaceshostsserviceswebsiteswebpagesdetailInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"hostid": {
			"type": "string",
			"title": "主机id",
			"description": "",
			"order": 2
		},
		"id": {
			"type": "string",
			"title": "Id",
			"description": "",
			"order": 5
		},
		"serviceid": {
			"type": "string",
			"title": "服务id",
			"description": "",
			"order": 3
		},
		"websitesid": {
			"type": "string",
			"title": "网站id",
			"description": "",
			"order": 4
		},
		"workspacesid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"workspacesid",
		"hostid",
		"serviceid",
		"websitesid",
		"id"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class WorkspaceshostsserviceswebsiteswebpagesdetailOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"data": {
			"type": "object",
			"title": "返回数据",
			"description": "",
			"order": 2
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
