# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    NAME = "name"
    REPORTS = "reports"
    

class Output:
    CODE = "code"
    MSG = "msg"
    REPORT = "report"
    

class MergeInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"name": {
			"type": "string",
			"title": "报表名字",
			"description": "",
			"order": 1
		},
		"reports": {
			"type": "array",
			"title": "报表列表",
			"description": "",
			"order": 2,
			"items": {
				"type": "string"
			}
		}
	},
	"required": [
		"reports"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class MergeOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"code": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		},
		"msg": {
			"type": "string",
			"title": "返回信息",
			"description": "",
			"order": 2
		},
		"report": {
			"title": "报表",
			"description": "",
			"order": 3,
			"$ref": "#/definitions/file"
		}
	},
	"required": [
		"code",
		"msg"
	],
	"definitions": {
		"file": {
			"id": "file",
			"type": "object",
			"title": "File",
			"description": "File Object",
			"properties": {
				"content": {
					"type": "string",
					"title": "Content",
					"description": "File contents",
					"format": "bytes"
				},
				"filename": {
					"type": "string",
					"title": "Filename",
					"description": "Name of file"
				}
			}
		}
	}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
