# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Input:
    TOKEN = "token"
    HOST = "host"
    

class ConnectionSchema(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"host": {
			"type": "string",
			"title": "url前缀",
			"description": "",
			"order": 2
		},
		"token": {
			"title": "唯一标识",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"token",
		"host"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)