# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    WORKSPACEID = "workspaceid"
    ADDRESSSTRING = "addressstring"
    BLACKSTRING = "blackstring"
    INITIALNMAP = "initialnmap"
    CUSTOMNMAP = "customnmap"
    PORTSEXTRA = "portsextra"
    PORTSBLACKLIST = "portsblacklist"
    PORTSCUSTOM = "portscustom"
    PORTSCANSOURCEPORT = "portscansourceport"
    FASTDETECT = "fastdetect"
    PORTTSCANSPEED = "porttscanspeed"
    PORTSCANTIMEOUT = "portscantimeout"
    UDPPROBES = "udpprobes"
    SNMPSCAN = "snmpscan"
    H323SCAN = "h323scan"
    FINGERUSERS = "fingerusers"
    IDENTIFYSERVICES = "identifyservices"
    SINGLESCAN = "singlescan"
    DRYRUN = "dryrun"
    INITIALWEBSCAN = "initialwebscan"
    SMBUSERNMAE = "smbusernmae"
    SMBPASSWORD = "smbpassword"
    SMBDOMAIN = "smbdomain"
    WEBSCANMAXPAGES = "webscanmaxpages"
    WEBSCANMAXMINUTE = "webscanmaxminute"
    WEBSCANMAXTHREADS = "webscanmaxthreads"
    AUTOTAGOS = "autotagos"
    HTTPUSERNAME = "httpusername"
    HTTPPASSWORD = "httppassword"
    HTTPDOMIAN = "httpdomian"
    COOKIE = "cookie"
    USERAGENT = "useragent"
    

class Output:
    STATUSCODE = "statuscode"
    SUCCESS = "success"
    WORKSPACEID = "workspaceid"
    TASKID = "taskid"
    ERRORS = "errors"
    

class TasksstartscanInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"addressstring": {
			"type": "string",
			"title": "目标地址",
			"description": "",
			"order": 2
		},
		"autotagos": {
			"type": "string",
			"title": "按擦作系统制动自动",
			"description": "",
			"order": 27
		},
		"blackstring": {
			"type": "string",
			"title": "排除地址",
			"description": "",
			"order": 3
		},
		"cookie": {
			"type": "string",
			"title": "http Cookie",
			"description": "",
			"order": 31
		},
		"customnmap": {
			"type": "string",
			"title": "自定义 Nmap 参数",
			"description": "",
			"order": 5
		},
		"dryrun": {
			"type": "boolean",
			"title": "只显示扫描信息",
			"description": "",
			"order": 19
		},
		"fastdetect": {
			"type": "boolean",
			"title": "快速扫描,仅适用tcp端口",
			"description": "",
			"order": 10
		},
		"fingerusers": {
			"type": "boolean",
			"title": "Finger枚举用户",
			"description": "",
			"order": 16
		},
		"h323scan": {
			"type": "boolean",
			"title": "h323视频节点扫描",
			"description": "",
			"order": 15
		},
		"httpdomian": {
			"type": "string",
			"title": "HTTP Domain",
			"description": "",
			"order": 30
		},
		"httppassword": {
			"type": "string",
			"title": "HTTP Password",
			"description": "",
			"order": 29,
			"displayType": "password",
			"format": "password"
		},
		"httpusername": {
			"type": "string",
			"title": "HTTP Username",
			"description": "",
			"order": 28
		},
		"identifyservices": {
			"type": "boolean",
			"title": "识别未知服务",
			"description": "",
			"order": 17
		},
		"initialnmap": {
			"type": "boolean",
			"title": "执行初始化端口扫描",
			"description": "",
			"order": 4
		},
		"initialwebscan": {
			"type": "boolean",
			"title": "运行web扫描",
			"description": "",
			"order": 20
		},
		"portsblacklist": {
			"title": "排除tcp端口",
			"description": "",
			"order": 7
		},
		"portscansourceport": {
			"type": "string",
			"title": "自定义tcp端口源端口",
			"description": "",
			"order": 9
		},
		"portscantimeout": {
			"type": "string",
			"title": "主机扫描时限",
			"description": "",
			"order": 12
		},
		"portscustom": {
			"type": "string",
			"title": "自定义tcp端口范围ie",
			"description": "",
			"order": 8
		},
		"portsextra": {
			"type": "boolean",
			"title": "添加tcp端口",
			"description": "",
			"order": 6
		},
		"porttscanspeed": {
			"type": "integer",
			"title": "端口扫描设置",
			"description": "",
			"order": 11,
			"enum": [
				0,
				1,
				2,
				3,
				4,
				5
			]
		},
		"singlescan": {
			"type": "boolean",
			"title": "单一扫描",
			"description": "",
			"order": 18
		},
		"smbdomain": {
			"type": "string",
			"title": "smp域",
			"description": "",
			"order": 23
		},
		"smbpassword": {
			"type": "string",
			"title": "SMP 密码",
			"description": "",
			"order": 22,
			"displayType": "password",
			"format": "password"
		},
		"smbusernmae": {
			"type": "string",
			"title": "SMB用户",
			"description": "",
			"order": 21
		},
		"snmpscan": {
			"type": "boolean",
			"title": "SNMP共同体名扫描",
			"description": "",
			"order": 14
		},
		"udpprobes": {
			"type": "boolean",
			"title": "udp服务探测",
			"description": "",
			"order": 13
		},
		"useragent": {
			"type": "string",
			"title": "用户代理",
			"description": "",
			"order": 32
		},
		"webscanmaxminute": {
			"type": "String",
			"title": "时间限制",
			"description": "",
			"order": 25
		},
		"webscanmaxpages": {
			"type": "String",
			"title": "最大爬行页数",
			"description": "",
			"order": 24
		},
		"webscanmaxthreads": {
			"type": "string",
			"title": "并发数",
			"description": "",
			"order": 26
		},
		"workspaceid": {
			"type": "string",
			"title": "任务id",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"workspaceid",
		"addressstring"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class TasksstartscanOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"errors": {
			"type": "string",
			"title": "错误信息",
			"description": "",
			"order": 5
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		},
		"success": {
			"type": "string",
			"title": "结果",
			"description": "",
			"order": 2
		},
		"taskid": {
			"type": "string",
			"title": "任务id",
			"description": "",
			"order": 4
		},
		"workspaceid": {
			"type": "string",
			"title": "项目id",
			"description": "",
			"order": 3
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
