# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    ID = "id"
    NAME = "name"
    DESCRIPTION = "description"
    BOUNDARY = "boundary"
    LIMIT_TO_NETWORK = "limit_to_network"
    

class Output:
    STATUSCODE = "statuscode"
    RESULT = "result"
    WORKSPACE = "workspace"
    

class WorkspacesupdateInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"boundary": {
			"type": "string",
			"title": "项目网络区间",
			"description": "",
			"order": 4
		},
		"description": {
			"type": "string",
			"title": "项目描述",
			"description": "",
			"order": 3
		},
		"id": {
			"type": "string",
			"title": "项目ID",
			"description": "",
			"order": 1
		},
		"limit_to_network": {
			"type": "string",
			"title": "是否限定网络范围",
			"description": "",
			"order": 5,
			"enum": [
				"0",
				"1"
			]
		},
		"name": {
			"type": "string",
			"title": "项目名称",
			"description": "",
			"order": 2
		}
	},
	"required": [
		"id",
		"name",
		"description",
		"boundary",
		"limit_to_network"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class WorkspacesupdateOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"result": {
			"type": "string",
			"title": "Result",
			"description": "",
			"order": 2
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		},
		"workspace": {
			"type": "object",
			"title": "Workspace",
			"description": "",
			"order": 3
		}
	},
	"required": [
		"statuscode",
		"result"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
