# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    WORKSPACEID = "workspaceid"
    

class Output:
    STATUSCODE = "statuscode"
    DATA = "data"
    

class WorkspacesreportsInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"workspaceid": {
			"type": "string",
			"title": "项目ID",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"workspaceid"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class WorkspacesreportsOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"data": {
			"type": "array",
			"title": "Data",
			"description": "",
			"order": 2,
			"items": {
				"type": "object"
			}
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
