# GENERATED BY CHARIOT SDK - DO NOT EDIT
import chariot
import json


class Component:
    DESCRIPTION = ""


class Input:
    REPORT = "report"
    

class Output:
    STATUSCODE = "statuscode"
    STATUS = "status"
    IDS = "ids"
    ERROR = "error"
    

class ValidatevulnsvalidateInput(chariot.Input):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"report": {
			"title": "倒入报文文件",
			"description": "",
			"order": 1,
			"$ref": "#/definitions/file"
		}
	},
	"required": [
		"report"
	],
	"definitions": {
		"file": {
			"id": "file",
			"type": "object",
			"title": "File",
			"description": "File Object",
			"properties": {
				"content": {
					"type": "string",
					"title": "Content",
					"description": "File contents",
					"format": "bytes"
				},
				"filename": {
					"type": "string",
					"title": "Filename",
					"description": "Name of file"
				}
			}
		}
	}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ValidatevulnsvalidateOutput(chariot.Output):
    schema = json.loads("""
   {
	"type": "object",
	"title": "Variables",
	"properties": {
		"error": {
			"type": "string",
			"title": "失败错误信息",
			"description": "",
			"order": 4
		},
		"ids": {
			"type": "object",
			"title": "[\u003c项目id\u003e， \u003c任务id\u003e]",
			"description": "",
			"order": 3
		},
		"status": {
			"type": "string",
			"title": "任务启动结果",
			"description": "",
			"order": 2,
			"enum": [
				"success",
				"fail"
			]
		},
		"statuscode": {
			"type": "integer",
			"title": "状态码",
			"description": "",
			"order": 1
		}
	},
	"required": [
		"statuscode"
	]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
