# -*- coding: utf-8 -*
# GENERATED BY CHARIOT SDK - DO NOT EDIT
from setuptools import setup, find_packages


setup(name='statisticsreport-chariot-plugin',
      version="0.1.0",
      description='集成统计各插件报告，并以规定格式返回',
      author='chariot',
      author_email='',
      url='',
      packages=find_packages(),
      scripts=['bin/chariot_statisticsreport']
      )